version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
    - npm install time
    - export BUCKET=lambda-deployment-artifact-118425
    - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
